language: python
python:
      - "2.7"
      - "3.6"
matrix:
      allow_failures:
            - python: "3.6"
sudo: false
install:
      - make setup
      - make update
      - nvm install 6.10
      - nvm use 6.10
before_script:
      - make lint-python
      - make lint-js
script:
      - make test
notifications:
      email: false
